STYLES = [
    "a scientific research abstract",
    "an informal chat message between friends",
    "a cooking recipe blog post",
    "a philosophical essay",
    "an instagram influencer caption",
    "a reddit AMA exchange",
    "legal contract language",
    "poetic verse on Tumblr",
    "an angry product review",
    "a political speech transcript",
    "technical documentation for software developers",
    "a formal job application email",
    "a sports commentary tweet",
    "a cybersecurity warning notification",
    "a personal journal entry",
    "a Youtube video description",
    "an inspirational linkedin post",
    "a travel destination guide",
    "a medical patient information leaflet",
    "a humorous satirical article",
    "an instruction manual",
    "an romantic fanfiction story excerpt",
    "a historical encyclopedia entry",
    "religious scripture quotations",
    "a conspiracy theory forum post",
    "a crowdfunding project description",
    "an academic literature review",
    "a multiple choice question",
    "product disclaimers and warnings",
    "parenting advice forum response",
    "a weather forecast bulletin",
    "a live sports event commentary",
    "an obituary notice",
    "a Wikipedia-style article summary",
    "an Amazon product description",
    "stock market analysis report",
    "a breaking news headline and blurb",
    "a corporate press release",
    "an online dating profile",
    "a motivational speech",
    "snarky Twitter exchange",
    "academic lecture notes",
    "a dramatic play script excerpt",
    "a historical documentary narration",
    "a coding tutorial",
    "comic dialogue speech bubbles",
    "a product unboxing video script",
    "a personal mental health confession",
    "satirical political commentary",
    "a Yelp restaurant review",
    "a space mission update from NASA",
    "a meditation guide",
    "technical product specifications",
    "song lyrics annotations",
    "a financial budget report",
    "a promotional newsletter email",
    "a interactive museum exhibit panel",
    "an enthusiastic review",
    "an event invitation",
    "an emergency broadcast alert message",
    "a transcript from a debate competition",
    "a privacy policy statement",
    "a fictional horror story",
    "hypothetical philosophical dialogue",
    "a linguistics academic paper excerpt",
    "memorable quotes compilation",
    "social media apology from a public figure",
    "cyberpunk-themed short story excerpt",
    "a horoscope daily prediction",
    "professional linkedin profile bio",
    "amateur poetry",
    "an inspirational personal testimony",
    "extremely short story",
    "very brief fiction",
    "concise fictional narrative",
    "brief evocative description",
    "song lyrics",
    "a japanese three-line poem",
    "a story about animals",
    "a children's magical story",
    "a myth"
    "a pithy observation",
    "dramatic soliloquy",
    "a private daily record",
    "a short depiction of a place",
    "short part of a public address",
    "brief notice of someone's death",
]